-- src/main/resources/schema.sql
-- Spring Data JDBC는 Hibernate DDL auto가 없으므로 테이블을 직접 정의한다
-- spring.sql.init.mode=always 설정 시 앱 시작 때 자동 실행됨

CREATE TABLE IF NOT EXISTS student (
   id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 자동 증가 기본키
   name  VARCHAR(100) NOT NULL,
   major VARCHAR(100) NOT NULL
);