-- [복사 위치] src/main/resources/schema.sql
-- [작업] 기존 파일을 이 파일로 교체

-- Spring Data JDBC: Hibernate DDL auto 없음 → 테이블 직접 정의
-- spring.sql.init.mode=always 설정 시 앱 시작 때 자동 실행 (application-h2.yml 참고)

CREATE TABLE IF NOT EXISTS student (
   id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name       VARCHAR(100) NOT NULL,
    student_id VARCHAR(20)  NOT NULL,   -- Java 필드 studentId → DB 컬럼 student_id (자동 매핑)
    email      VARCHAR(200)             -- NULL 허용 (이메일 선택 입력)
);
