CREATE TABLE IF NOT EXISTS student (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    student_id VARCHAR(20)  NOT NULL,
    email      VARCHAR(200),
    major      VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
